### ISSUE TITLE
ドメイン決め &登録

### ISSUE THREAD

**Issue by KnightOrKnave** [covid19-kitakyushu/covid19#15]
## 改善詳細 / Details of Improvement
- xxxx(できるだけ簡潔に/as concise as possible)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasuhiroIhara** [comment]
ドメインは、stopcovid19-kitakyushu.jp に決まり、三宅さんが取得するそうです。
サブドメインで、町や村のページにも対応する予定とのことです。

**Comment by LAC-Hiroki-Ikeda** [comment]
完了しました。
