### ISSUE TITLE
公開用AWSアカウント上での構築

### ISSUE THREAD

**Issue by YasuhiroIhara** [covid19-kitakyushu/covid19#19]
## ToDo
- 公開用のAWSアカウント取得後の環境構築
- 管理者アカウント、作業者アカウントを決める
- 本番用、ステージングの2環境を用意
- 本番用はcloudfrontで可用性を確保し、所定のドメインを設定

**Comment by LAC-Hiroki-Ikeda** [comment]
完了しました。
