### ISSUE TITLE
ロゴなどの確認

### ISSUE THREAD

**Issue by YasuhiroIhara** [covid19-kitakyushu/covid19#22]
## ToDo
- 初期立ち上げでは、Web上で取得したロゴを使用。正規のロゴに差し替えが必要
- faviconは市のサイトと同じものを流用済み

**Comment by KazumasaMiura** [comment]
ロゴを井原さん宛にメールさせていただきます。
（ここに直接載せるのは敢えて控えておきます。申し訳ないです。）

**Comment by YasuhiroIhara** [comment]
いただいたPDFデータを元に、pngファイルとsvgファイルを作成し、暫定版を置き換えました

**Comment by y2naranja** [comment]
失礼いたします。
スマホからみると、faviconが東京都のままです。ブラウザの履歴などでご確認ください。
