### ISSUE TITLE
xxxx/xx/xx xx:xx 更新の遷移先が機能していない

### ISSUE THREAD

**Issue by LAC-Ikeda** [covid19-kitakyushu/covid19#59]
## 改善詳細 / Details of Improvement
- xxxx(できるだけ簡潔に/as concise as possible)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasuhiroIhara** [comment]
この修正が難しければ、リンクを外しましょう
