### ISSUE TITLE
自動更新機能している？

### ISSUE THREAD

**Issue by LAC-Ikeda** [covid19-kitakyushu/covid19#60]
## 改善詳細 / Details of Improvement
- 先ほどブランチに保護かけていたためか手動で承認する必要があった
ちゃんとauto mergeされるか確認

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teraokaa** [comment]
auto-merge-botをインストールで解決しました。
