### ISSUE TITLE
最新のお知らせのリンクが仕様変更前の状態に戻っている

### ISSUE THREAD

**Issue by YasuhiroIhara** [covid19-kitakyushu/covid19#65]
## 起こっている問題 / The Problem
- 仕様変更で固定リンクを1つだけにしたが、複数のリンクが並ぶ状態に戻っている

## 期待する見せ方・挙動 / Expected Behavior
- 「最新のお知らせ」は以下への固定リンクとする
https://www.city.kitakyushu.lg.jp/kurashi/menu01_00274.html

## 起こっている問題の再現手段 / Steps to Reproduce
1. 本番環境を表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasuhiroIhara** [comment]
開発環境も同様。ニュースを取得するActionが動いているため?

**Comment by LAC-Ikeda** [comment]
news.jsonを更新しないようにしました
