### ISSUE TITLE
 お問い合わせ先一覧  書き換え

### ISSUE THREAD

**Issue by KnightOrKnave** [covid19-kitakyushu/covid19#8]
## 改善詳細 / Details of Improvement
-  お問い合わせ先一覧  の連絡先 局名を北九州市のものに変える

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by KazumasaMiura** [comment]
問い合わせ先も、どこかの部署に統一させるのか、
もしくは各部署ごとに設けるのかを確認いたします。
