### ISSUE TITLE
SNS リンク先 変えるか消す

### ISSUE THREAD

**Issue by KnightOrKnave** [covid19-kitakyushu/covid19#9]
## 改善詳細 / Details of Improvement
- SNSのリンク先を変える

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/4381960/79639170-e09a4080-81c4-11ea-994f-b77898cc2f1e.png)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasuhiroIhara** [comment]
* twitter, facebookは北九州市アカウントと思われるものに更新したが、要確認
* LINEもありそうだが、URL不明で東京のまま
* githubは本URLを設定済み

**Comment by KazumasaMiura** [comment]
SNSはどれを出すか確認します！

**Comment by YasuhiroIhara** [comment]
確認いただきました。以下のURLを設定します
https://www.facebook.com/city.of.kitakyushu/
https://twitter.com/city_kitakyushu/
https://page.line.me/zng7240n/
